[package]

name = "mandelbrot"
version = "0.0.1"
authors = [ "Nicolas Feltman <nfeltman@gmail.com>" ]


[dependencies]

time = "0.1"
num = "0.1.36"
num-complex = "0.1.35"
rayon = "0.5.0"
gtk = "0.1.0"
gdk-pixbuf = "0.1.0"
gdk-sys = "0.3.1"
